### ISSUE TITLE
Docker build DL part. Not Found for url: https://zenodo.org/record/4003545/files/Task009_Spleen.zip?download=1

### ISSUE THREAD

**Issue by krekiehn** [vastc/vastc#1]
Hi,
 
 i try to build the DL Docker on Debian Linux.
 

1.  First problem was "docker.io/nvidia/cuda:11.4.1-base-ubuntu20.04: not found". 

I solved that issue in chaning the first line of the dockerfile to "`FROM nvidia/cuda:11.4.3-base-ubuntu20.04`"

2. Next Problem is: "r`equests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://zenodo.org/record/4003545/files/Task009_Spleen.zip?download=1`" . The url works if you put it in the web browser.

Also `RUN curl -L -o Task009_Spleen.zip 'https://zenodo.org/record/4003545/files/Task009_Spleen.zip?download=1'` works. but i don't know how to use the downloaded file.

Full error message:
```

vastc/dl$ docker build -t vastc-pipeline .
[+] Building 0.9s (2/2) FINISHED                       docker:default
 => [internal] load build definition from Dockerfile             0.0s
 => => transferring dockerfile: 1.13kB                           0.0s
 => ERROR [internal] load metadata for docker.io/nvidia/cuda:11  0.8s
------
 > [internal] load metadata for docker.io/nvidia/cuda:11.4.1-base-ubuntu20.04:
------
Dockerfile:1
--------------------
   1 | >>> FROM nvidia/cuda:11.4.1-base-ubuntu20.04
   2 |     
   3 |     WORKDIR /app
--------------------
ERROR: failed to solve: nvidia/cuda:11.4.1-base-ubuntu20.04: failed to resolve source metadata for docker.io/nvidia/cuda:11.4.1-base-ubuntu20.04: docker.io/nvidia/cuda:11.4.1-base-ubuntu20.04: not found
"

 
 docker build -t vastc-pipeline .
[+] Building 1.2s (11/17)                                                                  docker:default
 => [internal] load build definition from Dockerfile                                                 0.0s
 => => transferring dockerfile: 1.13kB                                                               0.0s
 => [internal] load metadata for docker.io/nvidia/cuda:11.4.3-base-ubuntu20.04                       0.4s
 => [internal] load .dockerignore                                                                    0.0s
 => => transferring context: 2B                                                                      0.0s
 => [ 1/13] FROM docker.io/nvidia/cuda:11.4.3-base-ubuntu20.04@sha256:cb8622a77602d0d95f3cb7a8b7508  0.0s
 => [internal] load build context                                                                    0.0s
 => => transferring context: 161B                                                                    0.0s
 => CACHED [ 2/13] WORKDIR /app                                                                      0.0s
 => CACHED [ 3/13] RUN apt-get update && apt-get install -y python3 python3-pip curl git             0.0s
 => CACHED [ 4/13] RUN DEBIAN_FRONTEND=noninteractive apt-get install -y openjdk-17-jre-headless     0.0s
 => CACHED [ 5/13] RUN pip3 install torch torchvision torchaudio                                     0.0s
 => CACHED [ 6/13] RUN pip3 install nnunet                                                           0.0s
 => ERROR [ 7/13] RUN nnUNet_download_pretrained_model Task009_Spleen                                0.6s
------                                                                                                    
 > [ 7/13] RUN nnUNet_download_pretrained_model Task009_Spleen:                                           
0.537                                                                                                     
0.537                                                                                                     
0.537 Please cite the following paper when using nnUNet:                                                  
0.537                                                                                                     
0.537 Isensee, F., Jaeger, P.F., Kohl, S.A.A. et al. "nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation." Nat Methods (2020). https://doi.org/10.1038/s41592-020-01008-z
0.537 
0.537 
0.537 If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet
0.537 
0.537 
0.537 ######################################################
0.537 !!!!!!!!!!!!!!!!!!!!!!!!WARNING!!!!!!!!!!!!!!!!!!!!!!!
0.537 ######################################################
0.537 Using the pretrained model weights is subject to the license of the dataset they were trained on. Some allow commercial use, others don't. It is your responsibility to make sure you use them appropriately! Use nnUNet_print_pretrained_model_info(task_name) to see a summary of the dataset and where to find its license!
0.537 ######################################################
0.537 
0.537 Downloading pretrained model from url: https://zenodo.org/record/4003545/files/Task009_Spleen.zip?download=1
0.539 Traceback (most recent call last):
0.539   File "/usr/local/bin/nnUNet_download_pretrained_model", line 8, in <module>
0.539     sys.exit(download_by_name())
0.539   File "/usr/local/lib/python3.8/dist-packages/nnunet/inference/pretrained_models/download_pretrained_model.py", line 344, in download_by_name
0.539     download_and_install_pretrained_model_by_name(taskname)
0.539   File "/usr/local/lib/python3.8/dist-packages/nnunet/inference/pretrained_models/download_pretrained_model.py", line 260, in download_and_install_pretrained_model_by_name
0.539     download_and_install_from_url(url)
0.539   File "/usr/local/lib/python3.8/dist-packages/nnunet/inference/pretrained_models/download_pretrained_model.py", line 288, in download_and_install_from_url
0.539     raise e
0.539   File "/usr/local/lib/python3.8/dist-packages/nnunet/inference/pretrained_models/download_pretrained_model.py", line 283, in download_and_install_from_url
0.539     download_file(url=url, local_filename=tempfile, chunk_size=8192 * 16)
0.539   File "/usr/local/lib/python3.8/dist-packages/nnunet/inference/pretrained_models/download_pretrained_model.py", line 299, in download_file
0.539     r.raise_for_status()
0.539   File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 1024, in raise_for_status
0.539     raise HTTPError(http_error_msg, response=self)
0.539 requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://zenodo.org/record/4003545/files/Task009_Spleen.zip?download=1
------
Dockerfile:12
--------------------
  10 |     
  11 |     ENV nnUNet_raw_data_base="/app/nnUNet_raw" nnUNet_preprocessed="/app/nnUNet_preprocessed" RESULTS_FOLDER="/app/nnUNet_results"
  12 | >>> RUN nnUNet_download_pretrained_model Task009_Spleen
  13 |     
  14 |     RUN curl -L -o dcm4che-5.29.2-bin.tar.gz 'https://sourceforge.net/projects/dcm4che/files/dcm4che3/5.29.2/dcm4che-5.29.2-bin.tar.gz' && tar xvf dcm4che-5.29.2-bin.tar.gz && mv -v dcm4che-5.29.2 dcm4che && rm -f dcm4che-5.29.2-bin.tar.gz
--------------------
ERROR: failed to solve: process "/bin/sh -c nnUNet_download_pretrained_model Task009_Spleen" did not complete successfully: exit code: 1
```

**Comment by wlabelle** [comment]
Looks like that 404 error was fixed by the upstream project.
